/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "ITM.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void Custom_ITM(uint8_t data)
{
	DEMCR |= (1 << 24) ; /* Enable TRCENA */
	ITM_TER |= (1 << 0); /* Enable  Port 0 */
	while( !(ITM_STIM0 & 1) ); /* if ITM_STIM0 & 1 == 0 then it is busy */
	ITM_STIM0 = data ;
}

__attribute__ ((naked)) void Change_SP_To_PSP(void)
{
	/* Create symbolic name to the PSP start address " Same as #define PSP_ADDRESS 0x....." */
	__asm volatile(".equ MSP_STACK_START,(0x20000000 + (20*1024))");
	__asm volatile(".equ MSP_STACK_END,(MSP_STACK_START - 512)"); /* Assume MSP has only 512 Byte */
	__asm volatile(".equ PSP_STACK_START,MSP_STACK_END");

	/* Set the PSP to the created symbolic name */
	__asm volatile("LDR R3, =PSP_STACK_START");
	__asm volatile("MSR PSP, R3");

	/* Set the SPSEL in the CONTROL register to choose the PSP */
	__asm volatile("MOV R3, #0x0000002");
	__asm volatile("MSR CONTROL, R3");

	/* Return from the function to the main again as the compiler won't make
	   it automatically as we used naked attribute */
	__asm volatile("BX LR");
}

uint32_t Add_Five_Numbers(uint32_t num1 , uint32_t num2 , uint32_t num3 , uint32_t num4 , uint32_t num5)
{
	uint32_t TempNum = 5;
	uint32_t Summing = 0, TempNum1 = 55 , TempNum2 = 66 , TempNum3 = 77 ;

	Summing = num1 + num2 + num3 + num4 + num5 + TempNum1 + TempNum2 + TempNum3;
	TempNum += Summing;

	return TempNum ;
}

int main(void)
{

	/*		LEC 23		*/

//	Change_SP_To_PSP();
//
//
//	uint32_t PSP_STACK_START = 0x20004e00;
//	__asm volatile("MSR PSP,%0": : "r"(PSP_STACK_START));
//	__asm volatile("MSR CONTROL,%0": : "r"(2));

	/********************/

	/*		LEC 24		*/

//	uint32_t Result = Add_Five_Numbers(1,2,3,4,5);
//	Result++;

	/********************/

	for(;;);
}
